# Generated by Django 5.0.7 on 2024-07-17 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Corporation', 'Корпорация'), ('Company', 'Компания'), ('Firms', 'Фирма')], default='Company', max_length=120, unique=True, verbose_name='Категория')),
                ('slug', models.SlugField(blank=True, max_length=120, null=True, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Название Компании')),
                ('slug', models.SlugField(blank=True, max_length=120, null=True, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, unique=True, verbose_name='Описание')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Адрес')),
                ('contact_info', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('unique_code', models.CharField(max_length=5, unique=True, verbose_name='Уникальный код')),
                ('image', models.ImageField(blank=True, null=True, upload_to='company_images/', verbose_name='Изображение компании')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.category', verbose_name='Категория компании')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
            },
        ),
    ]
